name: "Install and cache npm dependencies"
description: "Install and cache npm dependencies"

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm ci
      shell: bash
